#!/bin/bash
# PostgreSQL Database Access Guide for BlinkPOS
# Server: track.twentyone.ist

echo "=== BlinkPOS Database Access Guide ==="
echo ""
echo "PostgreSQL Credentials:"
echo "  Host: postgres (in Docker network)"
echo "  Port: 5432"
echo "  Database: blinkpos"
echo "  User: blinkpos"
echo "  Password: E7SX47m5pi6e2CGfc2AdIs6LWD/rBf1pNvBoMbLFkMU="
echo ""
echo "Redis Credentials:"
echo "  Host: redis (in Docker network)"
echo "  Port: 6379"
echo "  Password: (none)"
echo ""
echo "=== Quick Access Commands ==="
echo ""
echo "1. Access PostgreSQL CLI:"
echo "   ssh ubuntu@track.twentyone.ist"
echo "   cd /var/www/blinkpos"
echo "   docker-compose -f docker-compose.prod.yml exec postgres psql -U blinkpos -d blinkpos"
echo ""
echo "2. Access Redis CLI:"
echo "   ssh ubuntu@track.twentyone.ist"
echo "   cd /var/www/blinkpos"
echo "   docker-compose -f docker-compose.prod.yml exec redis redis-cli"
echo ""
echo "3. View all payment splits:"
echo "   docker-compose -f docker-compose.prod.yml exec -T postgres psql -U blinkpos -d blinkpos -c 'SELECT * FROM payment_splits ORDER BY created_at DESC LIMIT 10;'"
echo ""
echo "4. View active payments:"
echo "   docker-compose -f docker-compose.prod.yml exec -T postgres psql -U blinkpos -d blinkpos -c 'SELECT * FROM active_payments;'"
echo ""
echo "5. Check payment stats:"
echo "   docker-compose -f docker-compose.prod.yml exec -T postgres psql -U blinkpos -d blinkpos -c 'SELECT status, COUNT(*) FROM payment_splits GROUP BY status;'"
echo ""
echo "6. View Redis keys:"
echo "   docker-compose -f docker-compose.prod.yml exec redis redis-cli KEYS 'blinkpos:*'"
echo ""
echo "7. Get specific payment from Redis:"
echo "   docker-compose -f docker-compose.prod.yml exec redis redis-cli GET 'blinkpos:payment:PAYMENT_HASH'"
echo ""

