apiVersion: vendir.k14s.io/v1alpha1
kind: Config

# Relative to ci/
directories:
- path: ../.github/workflows/vendor
  contents:
  - path: . # Copy this folder out to ..
    git:
      url: https://github.com/blinkbitcoin/concourse-shared.git
      ref: 2055dbe92df1048a2e77d8ac26480cba5d41aa0b
    includePaths:
    - shared/actions/*
    excludePaths:
    - shared/actions/rust-*
    - shared/actions/tofu-*
    newRootPath: shared/actions

- path: ./vendor
  contents:
  - path: .
    git:
      url: https://github.com/blinkbitcoin/concourse-shared.git
      ref: 2055dbe92df1048a2e77d8ac26480cba5d41aa0b
    includePaths:
    - shared/ci/**/*
    excludePaths:
    - shared/ci/**/rust-*
    - shared/ci/**/tofu-*
    newRootPath: shared/ci
